version: "3.7"
services:
  youtube-dl:
    image: hoanghiepitvnn/youtube-dl-aio
    container_name: youtube-dl
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    volumes:
      - ./downloads:/downloads
    command: |
      https://www.youtube.com/watch?v=HagVnWAeGcM
      -o "/downloads/%(title)s-%(duration)s.%(ext)s"
